name: jwt_generator
description: A package for generating JWT.
version: 0.0.1
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  pointycastle: ^3.9.1
  rsa_pkcs: ^2.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
