name: jwt_generator
description: A simple pure dart package used for creating and validating Json Web Tokens using the private and public key provided, refer to documentation for more information.
version: 0.0.3
repository: https://github.com/elijardh/jwt_generator

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  pointycastle: ^3.9.1
  rsa_pkcs: ^2.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

false_secrets:
  - "example/jwt_generator_example.dart" 
  - "README.md"